In [4]:
import pickle
import numpy as np

In [5]:
with open('D:\CMU_SDK_Dataset\mosi_train.pkl','rb') as f:
    data = pickle.load(f)


In [36]:
x = data[0][1]
print(type(x),x.shape,x)

<class 'numpy.float32'> () 2.4


In [52]:
data[0]

[[[array(['anyhow', 'it', 'was', 'really', 'good'], dtype='<U6'),
   array([[-1.6907e-01, -2.6402e-01, -2.2576e-01, ..., -3.5046e-01,
           -2.5917e-01,  2.8982e-01],
          [ 1.3629e-03,  3.5653e-01, -5.5497e-02, ..., -1.1237e-01,
            7.8259e-02,  2.2398e-01],
          [-4.4058e-02,  3.6611e-01,  1.8032e-01, ...,  1.8625e-01,
           -9.7817e-02, -6.7104e-05],
          [-2.1162e-01,  5.0881e-01, -3.5808e-01, ..., -1.8072e-01,
            2.8116e-01,  1.6978e-01],
          [-4.2625e-01,  4.4310e-01, -3.4517e-01, ..., -4.3030e-01,
           -6.8851e-02,  1.2875e-01]]),
   array([[ 0.25904375,  0.07814586, -0.00857246, ..., -0.21300621,
            0.30858484,  0.35417968],
          [ 0.29220742, -0.1817365 , -0.17717989, ...,  0.15445402,
            0.9803055 ,  0.15934856],
          [-0.08176315, -0.4176318 ,  0.23923877, ..., -0.6037879 ,
            0.9152047 , -0.8988941 ],
          ...,
          [ 0.11139152, -0.43235558,  0.7173777 , ..., -0.36167768,
 

In [55]:
data[0][0]

[[array(['anyhow', 'it', 'was', 'really', 'good'], dtype='<U6'),
  array([[-1.6907e-01, -2.6402e-01, -2.2576e-01, ..., -3.5046e-01,
          -2.5917e-01,  2.8982e-01],
         [ 1.3629e-03,  3.5653e-01, -5.5497e-02, ..., -1.1237e-01,
           7.8259e-02,  2.2398e-01],
         [-4.4058e-02,  3.6611e-01,  1.8032e-01, ...,  1.8625e-01,
          -9.7817e-02, -6.7104e-05],
         [-2.1162e-01,  5.0881e-01, -3.5808e-01, ..., -1.8072e-01,
           2.8116e-01,  1.6978e-01],
         [-4.2625e-01,  4.4310e-01, -3.4517e-01, ..., -4.3030e-01,
          -6.8851e-02,  1.2875e-01]]),
  array([[ 0.25904375,  0.07814586, -0.00857246, ..., -0.21300621,
           0.30858484,  0.35417968],
         [ 0.29220742, -0.1817365 , -0.17717989, ...,  0.15445402,
           0.9803055 ,  0.15934856],
         [-0.08176315, -0.4176318 ,  0.23923877, ..., -0.6037879 ,
           0.9152047 , -0.8988941 ],
         ...,
         [ 0.11139152, -0.43235558,  0.7173777 , ..., -0.36167768,
           0.0440779

In [63]:
data[0][0][0][1][0].__len__()

300

In [64]:
data[0][0][0][2][0].__len__()

768

In [107]:
data[1:3][1:3]

[[[[array(['i', 'mean', 'they', 'did', 'a', 'little', 'bit', 'of', 'it'],
          dtype='<U6'),
    array([[ 0.18733  ,  0.40595  , -0.51174  , ...,  0.16495  ,  0.18757  ,
             0.53874  ],
           [-0.48037  ,  0.14215  , -0.45985  , ...,  0.044432 ,  0.25162  ,
            -0.10527  ],
           [-0.13889  ,  0.10991  , -0.20471  , ..., -0.083825 ,  0.49241  ,
            -0.045157 ],
           ...,
           [-0.098027 ,  0.18014  ,  0.099034 , ..., -0.24725  , -0.1696   ,
             0.034731 ],
           [ 0.060216 ,  0.21799  , -0.04249  , ...,  0.11709  , -0.16692  ,
            -0.094085 ],
           [ 0.0013629,  0.35653  , -0.055497 , ..., -0.11237  ,  0.078259 ,
             0.22398  ]]),
    array([[ 0.41323853,  0.29526016,  0.02198068, ...,  0.03564891,
             0.44304517,  0.28058252],
           [ 0.285609  , -0.18917993, -0.06899448, ...,  0.4041443 ,
             1.2151668 ,  0.7114562 ],
           [ 1.3230473 , -0.3969216 , -0.36857596, ..., 

In [99]:
x = data[1][0][0][5][0]
print(x.shape, x)

(768,) [ 1.68504262e+00 -2.36457065e-01 -1.66147745e+00  5.05930305e-01
 -2.44131088e+00 -1.24195147e+00 -1.51321083e-01  9.88078773e-01
  1.14936090e+00 -3.45289767e-01  1.62985492e+00  2.99857795e-01
  1.66751161e-01 -1.24042535e+00 -1.79536507e-01  2.42584124e-01
 -9.64361489e-01 -1.44635439e-02 -4.62540150e-01  4.30772275e-01
 -8.83281469e-01 -1.20888603e+00  9.43959117e-01  5.46990156e-01
  5.18219769e-01 -4.01706100e-01  7.36410141e-01 -2.39274830e-01
 -1.60620284e+00  3.56772870e-01  2.71533757e-01  9.69807982e-01
 -3.20100594e+00 -2.46233791e-01  1.33840275e+00  1.21476352e+00
  3.28475386e-01  5.55238008e-01 -9.15170610e-01 -1.53979212e-02
 -2.86157894e+00  2.26401702e-01 -1.22696161e-02 -9.60627913e-01
 -1.44711244e+00 -1.14854968e+00 -1.71122570e+01  2.63915348e+00
 -2.22401187e-01 -1.05405676e+00  2.34571981e+00 -2.07614970e+00
 -6.23147249e-01  4.25330019e+00  1.52571893e+00  3.71424168e-01
 -1.41522872e+00  4.89471912e-01 -7.13154674e-03  1.55967832e+00
  1.59527993e+00  

In [5]:
import pickle
import pandas as pd
import numpy as np

In [6]:
fold_path = 'E:\\E-DAIC-WOZ\\splits'
with open(fold_path+'\\train.pkl','rb') as f :
  train = pickle.load(f)
  train = train['Participant_ID']
with open(fold_path+'\\dev.pkl','rb') as f :
  dev = pickle.load(f)
  dev = dev['Participant_ID']
with open(fold_path+'\\test.pkl','rb') as f :
  test = pickle.load(f)
  test = test['Participant_ID']
print(train, dev, test, sep='\n')

[302, 303, 304, 305, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 318, 319, 322, 323, 324, 325, 326, 327, 328, 329, 330, 332, 333, 335, 337, 338, 339, 340, 341, 345, 346, 348, 349, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 366, 367, 368, 369, 370, 372, 375, 376, 377, 378, 379, 380, 383, 384, 385, 386, 387, 389, 390, 391, 392, 395, 396, 397, 399, 400, 403, 404, 405, 406, 407, 409, 410, 411, 413, 414, 416, 417, 418, 419, 420, 421, 422, 424, 426, 427, 428, 429, 430, 432, 434, 436, 438, 439, 440, 443, 444, 445, 446, 447, 449, 450, 452, 453, 456, 457, 458, 459, 461, 462, 463, 464, 466, 467, 469, 470, 471, 472, 474, 476, 477, 478, 481, 482, 483, 485, 487, 488, 489, 490, 491, 492, 601, 603, 608, 612, 628, 633, 641, 654, 660, 662, 673, 677, 680, 684, 692, 695, 697, 702, 703, 707]
[300, 301, 306, 317, 320, 321, 331, 334, 336, 343, 344, 347, 350, 365, 371, 373, 374, 381, 382, 388, 393, 401, 402, 408, 412, 415, 423, 425, 431, 433, 435, 437, 441, 442, 448, 451, 454

In [276]:
type(file_path[0][:3])

str

In [279]:
import os
import pandas as pd
import pandas as pd

fold_path = 'D:\E-DAIC-WOZ\AUPOse'
file_path = os.listdir(fold_path)
n_list = []
train_list, dev_list, test_list = [], [], []
file_path.sort()
for i, file in enumerate(file_path):
  print(file[:3])
  if int(file[:3]) in train:
    train_list.append(pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore').iloc[:,4:].to_numpy())
  elif int(file[:3]) in dev:
    dev_list.append(pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore').iloc[:,4:].to_numpy())
  elif int(file[:3]) in test:
    test_list.append(pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore').iloc[:,4:].to_numpy())

with open(os.path.join(fold_path,'AUpose_train.pkl'),'wb') as f :
  pickle.dump(train_list, f)
with open(os.path.join(fold_path,'AUpose_dev.pkl'),'wb') as f :
  pickle.dump(dev_list, f)
with open(os.path.join(fold_path,'AUpose_test.pkl'),'wb') as f :
  pickle.dump(test_list, f)


300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
395
396
397
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
600
601
602
603
604
605
606
607
608
609
612
615
617
618
619
620
622
623
624
625
626
627
628
629
631
632
633
634
635
636
637
638
640
641
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
666
667
669
670
673
676
677
679
680
682
683


In [223]:
type(n_list[2])

numpy.ndarray

In [37]:
fold_path = 'E:\E-DAIC-WOZ\MFCC'
file_path = os.listdir(fold_path)
train_list, dev_list, test_list = [], [], []
file_path.sort()
for i, file in enumerate(file_path):

  print(file[:3])
  if int(file[:3]) in train:
    train_list.append(pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore', delimiter=';').iloc[:,4:].to_numpy())
  elif int(file[:3]) in dev:
    dev_list.append(pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore', delimiter=';').iloc[:,4:].to_numpy())
  elif int(file[:3]) in test:
    test_list.append(pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore', delimiter=';').iloc[:,4:].to_numpy())

with open(os.path.join(fold_path,'MFCC_train.pkl'),'wb') as f :
  pickle.dump(train_list, f)
with open(os.path.join(fold_path,'MFCC_dev.pkl'),'wb') as f :
  pickle.dump(dev_list, f)
with open(os.path.join(fold_path,'MFCC_test.pkl'),'wb') as f :
  pickle.dump(test_list, f)


300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
395
396
397
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
600
601
602
603
604
605
606
607
608
609
612
615
617
618
619
620
622
623
624
625
626
627
628
629
631
632
633
634
635
636
637
638
640
641
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
666
667
669
670
673
676
677
679
680
682
683


: 

In [35]:
train_list[0][0]

array([-4.757421e-02, -7.088384e+00,  1.317602e+00, -2.347494e+00,
        8.179334e+00, -1.260268e+01,  1.246894e+00, -6.084736e+00,
       -1.484699e+00, -2.239829e+00,  7.875562e+01, -1.612750e-01,
       -1.263511e+00,  3.611012e-01,  7.609813e-01, -7.102695e-01,
       -1.034821e+00, -2.089715e-01,  9.222811e-01, -2.161026e+00,
        5.123495e-01,  6.501927e-01,  1.651788e+00,  7.570198e-01,
       -7.125156e-02, -1.786204e-01, -5.876358e-01, -1.239905e-01,
       -1.518289e-01,  1.361543e-02, -8.364087e-02,  3.540182e-01,
        6.893204e-01, -6.338137e-01, -2.769489e-01, -4.129682e-02,
       -2.446632e-02])

In [294]:
fold_path = 'D:\E-DAIC-WOZ\\text'
file_path = os.listdir(fold_path)
train_list, dev_list, test_list = [], [], []
file_path.sort()
for i, file in enumerate(file_path):
  print(file[:3])
  if int(file[:3]) in train:
    rows = pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore').iloc[:,2]
    for r in rows:
      r = r.split()
    train_list.append(r)

  elif int(file[:3]) in dev:
    rows = pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore').iloc[:,2]
    for r in rows:
      r = r.split()
    dev_list.append(r)
  
  elif int(file[:3]) in test:
    rows = pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore').iloc[:,2]
    for r in rows:
      r = r.split()
    test_list.append(r)

with open(os.path.join(fold_path,'text_train.pkl'),'wb') as f :
  pickle.dump(train_list, f)
with open(os.path.join(fold_path,'text_dev.pkl'),'wb') as f :
  pickle.dump(dev_list, f)
with open(os.path.join(fold_path,'text_test.pkl'),'wb') as f :
  pickle.dump(test_list, f)


300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
395
396
397
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
600
601
602
603
604
605
606
607
608
609
612
615
617
618
619
620
622
623
624
625
626
627
628
629
631
632
633
634
635
636
637
638
640
641
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
666
667
669
670
673
676
677
679
680
682
683


In [299]:
train_list[2]

['but',
 "I'll",
 'be',
 'right',
 'there',
 'so',
 'I',
 "wasn't",
 'sure',
 'if',
 'that',
 'was',
 'part',
 'of',
 'it',
 'or',
 'not']

In [201]:
n_list

array([[-5.562058e+00,  4.949010e+00,  6.949461e+00, ..., -4.885251e-01,
        -5.119504e-01, -1.419785e-02],
       [-1.977317e-01, -4.952814e+00, -9.098467e-01, ..., -9.755176e-01,
        -8.811852e-01, -3.775005e-01],
       [-3.522472e+00, -7.440379e+00, -4.609577e+00, ..., -1.203045e+00,
        -9.164562e-01, -4.505925e-01],
       ...,
       [ 1.934180e+01, -1.268815e+01, -1.199065e+01, ..., -1.512828e-02,
         2.059142e+00, -1.069094e+00],
       [ 2.086686e+01, -1.241964e+01, -1.386796e+01, ..., -2.827167e-01,
         2.704793e+00, -6.500207e-01],
       [ 1.854416e+01, -4.095326e+00, -1.159590e+01, ..., -7.798643e-01,
         1.516611e+00, -4.948448e-02]])

In [260]:
fold_path = 'D:\E-DAIC-WOZ\splits'
# file_path = os.listdir(fold_path)
def make_labels(mode = 'train'):
  file = mode + '_split.csv'
  data = pd.read_csv(os.path.join(fold_path, file), header=0, encoding_errors='ignore')
  labels = {k:v.to_list() for k, v in data.items() }
  
  with open(os.path.join(fold_path, mode+'.pkl'),'wb') as f :
    pickle.dump(labels, f)
  
  return labels

data = make_labels(mode='dev')
data

#   n_list

{'Participant_ID': [300,
  301,
  306,
  317,
  320,
  321,
  331,
  334,
  336,
  343,
  344,
  347,
  350,
  365,
  371,
  373,
  374,
  381,
  382,
  388,
  393,
  401,
  402,
  408,
  412,
  415,
  423,
  425,
  431,
  433,
  435,
  437,
  441,
  442,
  448,
  451,
  454,
  455,
  465,
  468,
  473,
  475,
  479,
  480,
  484,
  486,
  617,
  627,
  632,
  653,
  657,
  667,
  670,
  687,
  698,
  713],
 'Gender': ['male',
  'male',
  'female',
  'male',
  'female',
  'female',
  'male',
  'male',
  'male',
  'male',
  'male',
  'male',
  'female',
  'male',
  'male',
  'male',
  'female',
  'male',
  'male',
  'male',
  'male',
  'female',
  'female',
  'female',
  'male',
  'female',
  'female',
  'female',
  'female',
  'male',
  'female',
  'male',
  'female',
  'male',
  'male',
  'female',
  'female',
  'female',
  'male',
  'male',
  'female',
  'male',
  'male',
  'male',
  'female',
  'female',
  'male',
  'male',
  'female',
  'female',
  'male',
  'male',
  'male',
  'ma

In [4]:
import pickle
fold_path = 'E:\E-DAIC-WOZ\splits'
# file_path = os.listdir(fold_path)
mode = 'train'
with open(os.path.join(fold_path, mode+'.pkl'),'rb') as f :
    l = pickle.load(f)

l

#   n_list

{'Participant_ID': [302,
  303,
  304,
  305,
  307,
  308,
  309,
  310,
  311,
  312,
  313,
  314,
  315,
  316,
  318,
  319,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  332,
  333,
  335,
  337,
  338,
  339,
  340,
  341,
  345,
  346,
  348,
  349,
  351,
  352,
  353,
  354,
  355,
  356,
  357,
  358,
  359,
  360,
  361,
  362,
  363,
  364,
  366,
  367,
  368,
  369,
  370,
  372,
  375,
  376,
  377,
  378,
  379,
  380,
  383,
  384,
  385,
  386,
  387,
  389,
  390,
  391,
  392,
  395,
  396,
  397,
  399,
  400,
  403,
  404,
  405,
  406,
  407,
  409,
  410,
  411,
  413,
  414,
  416,
  417,
  418,
  419,
  420,
  421,
  422,
  424,
  426,
  427,
  428,
  429,
  430,
  432,
  434,
  436,
  438,
  439,
  440,
  443,
  444,
  445,
  446,
  447,
  449,
  450,
  452,
  453,
  456,
  457,
  458,
  459,
  461,
  462,
  463,
  464,
  466,
  467,
  469,
  470,
  471,
  472,
  474,
  476,
  477,
  478,
  481,
  482,
  483,
  485,
  487,
  488,
  489,
  

In [6]:
l.keys()

dict_keys(['Participant_ID', 'Gender', 'PHQ_Binary', 'PHQ_Score', 'PCL-C (PTSD)', 'PTSD Severity'])

In [9]:
import numpy as np
with open('E:\E-DAIC-WOZ\MFCC\\MFCC_train.pkl','rb') as f :
    n = np.load(f, allow_pickle= True)
n

[array([[ -0.04757421,  -7.088384  ,   1.317602  , ...,  -0.2769489 ,
          -0.04129682,  -0.02446632],
        [ -0.3591341 , -13.74769   ,  -3.611933  , ...,  -0.7023283 ,
          -0.9684782 ,  -0.1134517 ],
        [  1.913712  ,   0.04617836,   0.2310219 , ...,  -0.9323754 ,
          -1.364911  ,  -0.2123388 ],
        ...,
        [ -2.285791  ,  -6.663337  ,   0.01565316, ...,  -0.7322412 ,
          -0.858568  ,   0.04780731],
        [ -1.768871  ,  -4.910288  ,   9.39424   , ...,   0.2543516 ,
          -0.2886717 ,   0.1542705 ],
        [  7.364503  ,   0.2295596 ,   3.574549  , ...,   0.6521921 ,
           0.5182637 ,   0.06397362]]),
 array([[-2.519692  , -6.073299  ,  0.3544745 , ...,  0.8361109 ,
         -0.01214546,  0.1966402 ],
        [ 0.134716  , -3.653686  ,  2.318593  , ...,  0.6424699 ,
          0.2550018 ,  0.3484513 ],
        [ 3.926397  , -3.117132  ,  4.903048  , ...,  0.472711  ,
          0.608214  ,  0.2511376 ],
        ...,
        [-3.498523

In [18]:
n[1]

array([[-2.519692  , -6.073299  ,  0.3544745 , ...,  0.8361109 ,
        -0.01214546,  0.1966402 ],
       [ 0.134716  , -3.653686  ,  2.318593  , ...,  0.6424699 ,
         0.2550018 ,  0.3484513 ],
       [ 3.926397  , -3.117132  ,  4.903048  , ...,  0.472711  ,
         0.608214  ,  0.2511376 ],
       ...,
       [-3.498523  , -1.919887  , -0.2177838 , ...,  1.640867  ,
         0.1836125 ,  0.06205345],
       [-2.345882  , -2.577387  ,  4.719168  , ...,  1.322019  ,
         0.6677663 , -0.04626144],
       [ 0.3950777 , -0.1724977 , 10.84774   , ...,  0.06238298,
         0.6024953 , -0.01785294]])